name: Java CI with Gradle

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      runTests:
        description: 'Run tests'
        required: true
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
        type: choice
        options:
          - 'debug'
          - 'info'              
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Execute Gradle build
        run: |
          if [[ "${{ github.event.inputs.runTests }}" == 'true' ]]; then
            ./gradlew build
          else
            ./gradlew build -x test
          fi